---
version: "3"

services:

  ui:
    image: fabioandreola/github-top-contributors-ui
    ports:
      - 80:80
    links: 
      - github-top-contributors-app:api.githubtopcontributors

  github-top-contributors-app:
    image: fabioandreola/github-top-contributors
    env_file: 
      - github-top-contributors-app-test.env
    ports:
      - 8080
