spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}


application:
  github.graphql.url: "https://api.github.com/graphql"
server:
  forward-headers-strategy: framework
