apiVersion: v1
kind: Namespace
metadata:
  name: githubtopcontributors
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: githubtopcontributors
  namespace: githubtopcontributors
---
apiVersion: v1
kind: Secret
metadata:
  name: githubtopcontributors-secret-env
  namespace: githubtopcontributors
type: Opaque
data:
  client-id: OTFiNTc1NmJmNjZlZDk0ZWM5ZGQ=
  client-secret: Njc4ZDQ4YzIyZWIxNWNjNTE0ZThiYTI5ZGNiNzkxYThhYTgxNDhjMw==
  redis-password: cGdhc3c5aXN4b2Ewb3ZnMQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: githubtopcontributors-config-env
  namespace: githubtopcontributors
data:
  redis-host: db-redis-fra1-70659-do-user-6980430-0.db.ondigitalocean.com
  redis-port: "25061"
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: githubtopcontributors
spec:
  type: LoadBalancer
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 80
  selector:
    app: ui
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: githubtopcontributors
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/part-of: githubtopcontributors
    app.kubernetes.io/version: v1
  name: ui
  namespace: githubtopcontributors
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - env:
            - name: HTTP_PORT
              value: "80"
          image: fabioandreola/github-top-contributors-ui:latest
          name: ui
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
      serviceAccountName: githubtopcontributors
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: githubtopcontributors
    app.kubernetes.io/version: v1
  name: api
  namespace: githubtopcontributors
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: githubtopcontributors-secret-env
                  key: client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: githubtopcontributors-secret-env
                  key: client-secret
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: githubtopcontributors-secret-env
                  key: redis-password
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: githubtopcontributors-config-env
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: githubtopcontributors-config-env
                  key: redis-port
          image: fabioandreola/github-top-contributors:latest
          name: api
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      serviceAccountName: githubtopcontributors

