name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: docker build backend api
      run: |
        docker build . -t fabioandreola/github-top-contributors:latest
    - name: docker build ui
      run: |
        docker build ./ui -t fabioandreola/github-top-contributors-ui:latest
    - name: docker push
      run: |
        docker push fabioandreola/github-top-contributors:latest
        docker push fabioandreola/github-top-contributors-ui:latest
